{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":24542,"status":"ok","timestamp":1701675545161,"user":{"displayName":"Regan Shen","userId":"00528300591745974743"},"user_tz":-120},"id":"RDh7SM5Jo-XG","outputId":"1251c143-7de7-4cc9-d019-c22a264bc5f7"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n","/content/drive/My Drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')\n","%cd drive/My Drive"]},{"cell_type":"code","execution_count":16,"metadata":{"colab":{"background_save":true},"executionInfo":{"elapsed":363,"status":"ok","timestamp":1701685227025,"user":{"displayName":"Regan Shen","userId":"00528300591745974743"},"user_tz":-120},"id":"BtYGRNp_pH1T"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-26-ddc5e13ad265\u003e\", line 6, in \u003ccell line: 6\u003e\n","    import tensorflow as tf\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-26-ddc5e13ad265\u003e\", line 6, in \u003ccell line: 6\u003e\n","    import tensorflow as tf\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-26-ddc5e13ad265\u003e\", line 6, in \u003ccell line: 6\u003e\n","    import tensorflow as tf\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1027, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1002, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 945, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1439, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1408, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1366, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["import pandas as pd\n","import numpy as np\n","\n","import matplotlib.pyplot as plt\n","from datetime import datetime"]},{"cell_type":"code","execution_count":22,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":8413,"status":"ok","timestamp":1701688261207,"user":{"displayName":"Regan Shen","userId":"00528300591745974743"},"user_tz":-120},"id":"M7NdyjFQpTUE","outputId":"d573369a-b1d7-45b3-b992-6eb8e0642c72"},"outputs":[{"name":"stdout","output_type":"stream","text":["     tempmax  tempmin     temp  feelslikemax  feelslikemin  feelslike  \\\n","0    30.2875  16.7500  23.1125       29.4625       16.7500    22.8500   \n","1    29.1500  16.3875  22.7625       28.9375       16.3875    22.6750   \n","2    29.5250  17.0250  22.8125       29.6375       17.0250    22.7875   \n","3    27.7500  16.8500  21.8625       27.7875       16.8500    21.8500   \n","4    23.8250  15.8125  19.4875       23.5750       15.8125    19.4500   \n","..       ...      ...      ...           ...           ...        ...   \n","646  30.2625  14.5375  22.3250       29.1625       14.5375    21.9625   \n","647  28.8000  16.8625  22.4125       28.3625       16.8625    22.1875   \n","648  27.1750  15.5750  21.2625       26.2000       15.5750    20.9875   \n","649  27.8250  13.5625  20.8500       26.8375       13.5625    20.5750   \n","650  27.6125  15.3750  21.4500       26.3250       15.3750    21.0000   \n","\n","         dew  humidity    precip  precipprob  ...  sealevelpressure  \\\n","0    13.4750   60.8750  0.021500        25.0  ...         1017.4750   \n","1    14.5375   63.0250  2.250000        12.5  ...         1015.2250   \n","2    15.0250   65.6500  0.042500        37.5  ...         1013.7500   \n","3    14.4625   66.7375  0.106875        50.0  ...         1014.1500   \n","4    13.0875   70.4875  3.461500        75.0  ...         1015.7500   \n","..       ...       ...       ...         ...  ...               ...   \n","646  11.0625   57.3750  0.000375        12.5  ...         1016.4125   \n","647  11.7500   57.9250  0.000500        25.0  ...         1016.4375   \n","648   9.1375   51.5750  0.666125        62.5  ...         1020.2000   \n","649   9.1875   55.8375  0.426250        25.0  ...         1020.9625   \n","650   8.2875   53.5875  0.700625        25.0  ...         1020.5000   \n","\n","     cloudcover  visibility  solarradiation  solarenergy  uvindex  severerisk  \\\n","0       31.6750     14.3625        296.0500      25.6125    9.000      10.000   \n","1       28.2875     13.8875        316.5250      27.3750    9.500      10.000   \n","2       36.9000     14.1000        323.4125      27.9625    9.625      11.875   \n","3       46.2000     14.0875        297.9000      25.8000    9.000      10.000   \n","4       56.0875     13.7875        204.2875      17.6500    6.750      10.000   \n","..          ...         ...             ...          ...      ...         ...   \n","646     19.1625     16.4625        322.1375      27.8500    9.625      10.000   \n","647     40.5625     16.4500        307.1125      26.5250    9.625      12.500   \n","648     28.6625     16.1875        292.2750      25.2375    8.875      10.000   \n","649     31.7875     16.5500        287.3750      24.8625    9.125      10.000   \n","650     43.0750     17.2125        246.8500      21.3250    7.125      10.000   \n","\n","     moonphase  icon  Total_RE  \n","0         0.31     0  50139.77  \n","1         0.34     3  53866.52  \n","2         0.38     3  61662.47  \n","3         0.41     1  60115.65  \n","4         0.45     1  69114.93  \n","..         ...   ...       ...  \n","646       0.90     0  50606.49  \n","647       0.94     3  69288.65  \n","648       0.97     1  56013.14  \n","649       0.00     0  60582.18  \n","650       0.04     3  65043.78  \n","\n","[651 rows x 26 columns]\n"]}],"source":["def extract_Total_RE(eskom_dataframe, dictOfDates):\n","    for index, row in eskom_dataframe.iterrows():\n","        # Accessing values\n","        column1_value = row['Date']\n","        date_obj = datetime.strptime(column1_value, '%A, %d %B %Y')\n","        formatted_date = date_obj.strftime('%Y/%m/%d')\n","        if formatted_date in dictOfDates:\n","            tRE = dictOfDates[formatted_date]\n","            temp = tRE + row['Total_RE']\n","            dictOfDates[formatted_date] = temp\n","    return dictOfDates\n","\n","\n","def analyize_Weather(weather_df):\n","    DictionaryOfWeather = {}\n","    for index, row in weather_df.iterrows():\n","        DateTime = row['datetime']\n","        date_obj = datetime.strptime(DateTime, '%Y/%m/%d')\n","\n","        formatted_date = date_obj.strftime('%Y/%m/%d')\n","        DictionaryOfWeather[formatted_date] = 0\n","\n","    return DictionaryOfWeather\n","\n","def preprocess_weather(weather_df, dictionaryOfDates, theTotalRE):\n","    #Here I will remove all the unnecassiry columns\n","    #And binary encode certain values\n","    weather_df.drop('conditions', axis=1, inplace=True)\n","    weather_df.drop('description', axis=1, inplace=True)\n","    weather_df.drop('stations', axis=1, inplace=True)\n","    weather_df.drop('sunrise', axis=1, inplace=True)\n","    weather_df.drop('sunset', axis=1, inplace=True)\n","    weather_df.drop('preciptype', axis=1, inplace=True)\n","\n","    columns_to_drop = [col for col in weather_df.columns if 'Unnamed' in col]\n","\n","    # Dropping the columns\n","    weather_df.drop(columns=columns_to_drop, inplace=True)\n","    icon_mapping = {\n","        'clear-day': 0,\n","        'rain': 1,\n","        'wind': 2,\n","        'partly-cloudy-day': 3,\n","        'cloudy': 4\n","    }\n","    weather_df['icon'] = weather_df['icon'].replace(icon_mapping)\n","    return average_locations(weather_df,dictionaryOfDates,theTotalRE)\n","def average_locations(weather_df, dictionaryOfDates,theTotalRE):\n","    finalVersion = pd.DataFrame()\n","    for x in dictionaryOfDates:\n","        results = weather_df.loc[weather_df[\"datetime\"] == x]\n","        # Avoid SettingWithCopyWarning by creating a new DataFrame directly\n","        results = results.drop('name', axis=1)\n","        results = results.drop('datetime', axis=1)\n","        # Select only numerical columns for calculating the mean\n","        # Select only numerical columns except 'icon' for calculating the mean\n","        numerical_cols = results.select_dtypes(include=['number'])\n","\n","        # Calculating the average for each numerical field except 'icon'\n","        averages = numerical_cols.mean()\n","\n","        # Calculating the median for 'icon'\n","        icon_median = results['icon'].mode()\n","\n","        # Creating a new DataFrame with the averages\n","        average_df = averages.to_frame().transpose()\n","\n","        # Adding the median of 'icon' to the DataFrame\n","        average_df['icon'] = icon_median\n","        average_df['Total_RE'] = theTotalRE[x]\n","        finalVersion = pd.concat([finalVersion, average_df], ignore_index=True)\n","    finalVersion = finalVersion.dropna(subset=['Total_RE'])\n","\n","    for column in finalVersion.columns:\n","      if finalVersion[column].isna().any():  # Check if there are any NaN values in the column\n","          mean_value = finalVersion[column].mean()  # Calculate the mean of the column\n","          finalVersion[column].fillna(mean_value, inplace=True)  # Replace NaNs with the mean value\n","    return finalVersion\n","\n","def readInputFile(pathForWeather, pathForEskom):\n","    dfweather = pd.read_csv(pathForWeather)\n","    dfeskomData = pd.read_csv(pathForEskom)\n","    dict_of_dates = analyize_Weather(dfweather)\n","    theTotalRE = extract_Total_RE(dfeskomData,dict_of_dates)\n","    preprossed_df = preprocess_weather(dfweather,dict_of_dates,theTotalRE)\n","    return preprossed_df\n","\n","preprossed_df = readInputFile('/content/drive/MyDrive/SACAIR-Hackathon-2023-TheWeather/Data/WeatherData.csv', '/content/drive/MyDrive/SACAIR-Hackathon-2023-TheWeather/Data/EskomData.csv')\n","print(preprossed_df)\n","normalized_df = (preprossed_df - preprossed_df.min()) / (preprossed_df.max() - preprossed_df.min())\n","preprossed_df = normalized_df"]},{"cell_type":"code","execution_count":25,"metadata":{"executionInfo":{"elapsed":493,"status":"ok","timestamp":1701690583114,"user":{"displayName":"Regan Shen","userId":"00528300591745974743"},"user_tz":-120},"id":"2uBm2llqhfvP"},"outputs":[],"source":["normalized_df = (preprossed_df - preprossed_df.min()) / (preprossed_df.max() - preprossed_df.min())\n","normalized_df.to_csv('/content/drive/MyDrive/SACAIR-Hackathon-2023-TheWeather/Data/processed.csv',index=False)"]}],"metadata":{"colab":{"name":"","version":""},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.10"}},"nbformat":4,"nbformat_minor":0}
